/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mcd.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EvCustom extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -907545401220592809L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EvCustom\",\"namespace\":\"com.mcd.avro\",\"fields\":[{\"name\":\"Info\",\"type\":{\"type\":\"record\",\"name\":\"Info\",\"fields\":[{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"data\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EvCustom> ENCODER =
      new BinaryMessageEncoder<EvCustom>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EvCustom> DECODER =
      new BinaryMessageDecoder<EvCustom>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EvCustom> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EvCustom> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EvCustom> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EvCustom>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EvCustom to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EvCustom from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EvCustom instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EvCustom fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.mcd.avro.Info Info;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EvCustom() {}

  /**
   * All-args constructor.
   * @param Info The new value for Info
   */
  public EvCustom(com.mcd.avro.Info Info) {
    this.Info = Info;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Info;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Info = (com.mcd.avro.Info)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Info' field.
   * @return The value of the 'Info' field.
   */
  public com.mcd.avro.Info getInfo() {
    return Info;
  }


  /**
   * Sets the value of the 'Info' field.
   * @param value the value to set.
   */
  public void setInfo(com.mcd.avro.Info value) {
    this.Info = value;
  }

  /**
   * Creates a new EvCustom RecordBuilder.
   * @return A new EvCustom RecordBuilder
   */
  public static com.mcd.avro.EvCustom.Builder newBuilder() {
    return new com.mcd.avro.EvCustom.Builder();
  }

  /**
   * Creates a new EvCustom RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EvCustom RecordBuilder
   */
  public static com.mcd.avro.EvCustom.Builder newBuilder(com.mcd.avro.EvCustom.Builder other) {
    if (other == null) {
      return new com.mcd.avro.EvCustom.Builder();
    } else {
      return new com.mcd.avro.EvCustom.Builder(other);
    }
  }

  /**
   * Creates a new EvCustom RecordBuilder by copying an existing EvCustom instance.
   * @param other The existing instance to copy.
   * @return A new EvCustom RecordBuilder
   */
  public static com.mcd.avro.EvCustom.Builder newBuilder(com.mcd.avro.EvCustom other) {
    if (other == null) {
      return new com.mcd.avro.EvCustom.Builder();
    } else {
      return new com.mcd.avro.EvCustom.Builder(other);
    }
  }

  /**
   * RecordBuilder for EvCustom instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EvCustom>
    implements org.apache.avro.data.RecordBuilder<EvCustom> {

    private com.mcd.avro.Info Info;
    private com.mcd.avro.Info.Builder InfoBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mcd.avro.EvCustom.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Info)) {
        this.Info = data().deepCopy(fields()[0].schema(), other.Info);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasInfoBuilder()) {
        this.InfoBuilder = com.mcd.avro.Info.newBuilder(other.getInfoBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing EvCustom instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mcd.avro.EvCustom other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.Info)) {
        this.Info = data().deepCopy(fields()[0].schema(), other.Info);
        fieldSetFlags()[0] = true;
      }
      this.InfoBuilder = null;
    }

    /**
      * Gets the value of the 'Info' field.
      * @return The value.
      */
    public com.mcd.avro.Info getInfo() {
      return Info;
    }


    /**
      * Sets the value of the 'Info' field.
      * @param value The value of 'Info'.
      * @return This builder.
      */
    public com.mcd.avro.EvCustom.Builder setInfo(com.mcd.avro.Info value) {
      validate(fields()[0], value);
      this.InfoBuilder = null;
      this.Info = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Info' field has been set.
      * @return True if the 'Info' field has been set, false otherwise.
      */
    public boolean hasInfo() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'Info' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.mcd.avro.Info.Builder getInfoBuilder() {
      if (InfoBuilder == null) {
        if (hasInfo()) {
          setInfoBuilder(com.mcd.avro.Info.newBuilder(Info));
        } else {
          setInfoBuilder(com.mcd.avro.Info.newBuilder());
        }
      }
      return InfoBuilder;
    }

    /**
     * Sets the Builder instance for the 'Info' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.mcd.avro.EvCustom.Builder setInfoBuilder(com.mcd.avro.Info.Builder value) {
      clearInfo();
      InfoBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'Info' field has an active Builder instance
     * @return True if the 'Info' field has an active Builder instance
     */
    public boolean hasInfoBuilder() {
      return InfoBuilder != null;
    }

    /**
      * Clears the value of the 'Info' field.
      * @return This builder.
      */
    public com.mcd.avro.EvCustom.Builder clearInfo() {
      Info = null;
      InfoBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EvCustom build() {
      try {
        EvCustom record = new EvCustom();
        if (InfoBuilder != null) {
          try {
            record.Info = this.InfoBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("Info"));
            throw e;
          }
        } else {
          record.Info = fieldSetFlags()[0] ? this.Info : (com.mcd.avro.Info) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EvCustom>
    WRITER$ = (org.apache.avro.io.DatumWriter<EvCustom>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EvCustom>
    READER$ = (org.apache.avro.io.DatumReader<EvCustom>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.Info.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.Info == null) {
        this.Info = new com.mcd.avro.Info();
      }
      this.Info.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.Info == null) {
            this.Info = new com.mcd.avro.Info();
          }
          this.Info.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










